### ISSUE TITLE
no dimensions.json for W8LS26616

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/volume-manifest-builder#37] opened 2020-11-03 16:00 UTC
Transferred from [archive-ops-195](https://github.com/buda-base/archive-ops/issues/195) 

Need to allow image groups to not exist inside v-m-b

**Comment by eroux** [comment] 2020-11-03 16:38
Here's a list of works that might have the same problem. Not all of them do but once the issue is closed, maybe we could rerun the vmb on these too? Thanks!

[faileddim.txt](https://github.com/buda-base/volume-manifest-builder/files/5482675/faileddim.txt)

**Comment by jimk-bdrc** [comment] 2020-11-03 19:37
```
/Users/jimk/dev/volume-manifest-builder/venv/bin/python -m manifestBuilder -l . -d debug -w W8LS26616 fs -c /Volumes/home/prod/
INFO - Volume I8LS26621 processing: 035.2 sec 
INFO - Volume I8LS26622 processing: 039.4 sec 
ERROR - No manifest created for  I8LS26623 
ERROR - No manifest created for  I8LS26624 
ERROR - No manifest created for  I8LS26625 
ERROR - No manifest created for  I8LS26626 
ERROR - No manifest created for  I8LS26627 
ERROR - No manifest created for  I8LS26628 

Process finished with exit code 0
```
Set it up to not fail, but continue trying. The log has errors, but the process still returns with 0.

**Comment by jimk-bdrc** [comment] 2020-11-03 19:38
I'll re-run faileddims.txt on a server after I check in and rebuild.

**Comment by jimk-bdrc** [comment] 2020-11-04 16:31
I ran `manifestforwork  -l . -d debug -f ~/home/prod/faileddim.txt fs -c /mnt/rs5Archive` all set. That uploaded to our servers.

I ran `manifestforwork  -l . -d debug -f faileddim.txt s3  -b  archive.tbrc.org` put the dimensions up on the web.

The pyPI release for this is bdrc-volume-manifest-tool 1.1.2

**Comment by jimk-bdrc** [comment] 2020-11-04 16:33
I ran `manifestforwork  -l . -d debug -f ~/home/prod/faileddim.txt fs -c /mnt/rs5Archive` all set. That uploaded to our servers.

I ran `manifestforwork  -l . -d debug -f faileddim.txt s3  -b  archive.tbrc.org` put the dimensions up on the web.

The pyPI release for this is bdrc-volume-manifest-tool 1.1.2

**Comment by eroux** [comment] 2020-11-04 16:35
excellent, thanks! W8LS26616 works now. I'm ok to close this issue

**Closed as completed** 2020-11-04 16:39 UTC
Labels: enhancement
